In [2]:
import torch

In [10]:
a=torch.tensor([[1,1,1],[1,0,1],[0,1,1],[0,1,0],[1,1,1]])
g= torch.randint(2,(8,8))
g[0]=torch.ones(8)
g[:,0]= torch.ones(8)
a,g

(tensor([[1, 1, 1],
         [1, 0, 1],
         [0, 1, 1],
         [0, 1, 0],
         [1, 1, 1]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 0, 1, 0, 0, 0, 1],
         [1, 1, 1, 0, 1, 1, 0, 1],
         [1, 1, 1, 0, 1, 0, 1, 0],
         [1, 1, 1, 1, 1, 0, 0, 0],
         [1, 0, 1, 0, 0, 1, 1, 1],
         [1, 0, 0, 0, 0, 0, 1, 0],
         [1, 1, 1, 0, 0, 0, 0, 1]]))

In [16]:
bool= g!=0
(bool).int()

tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 0, 0, 0, 1],
        [1, 1, 1, 0, 1, 1, 0, 1],
        [1, 1, 1, 0, 1, 0, 1, 0],
        [1, 1, 1, 1, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 1, 1],
        [1, 0, 0, 0, 0, 0, 1, 0],
        [1, 1, 1, 0, 0, 0, 0, 1]], dtype=torch.int32)

In [5]:
row,indice=torch.min(g,axis=1)
row,indice

(tensor([ True, False, False, False, False, False, False, False]),
 tensor([0, 1, 1, 1, 1, 4, 2, 1]))

In [6]:
minrow=torch.argmin(row)

RuntimeError: "argmin_cpu" not implemented for 'Bool'

In [34]:
row,indice=torch.min(g,axis=1)
row,indice


(tensor([1, 0, 0, 0, 0, 0, 0, 0]), tensor([0, 1, 1, 2, 3, 3, 1, 1]))

In [35]:
minrow=torch.argmin(row)
maxrow = row.shape[0]-torch.argmin(row.flip(0))-1
minrow,maxrow

(tensor(1), tensor(7))

In [36]:
col, _ =torch.min(g,axis=0)
mincol=torch.argmin(col)
maxcol=col.shape[0]-torch.argmin(col.flip(0))-1
col,mincol,maxcol

(tensor([1, 0, 0, 0, 0, 0, 0, 0]), tensor(1), tensor(7))

In [37]:
aa=g[minrow:maxrow+1,mincol:maxcol+1]
aa# 查看截取位置

tensor([[0, 1, 0, 1, 1, 0, 1],
        [0, 1, 1, 0, 0, 1, 0],
        [1, 0, 1, 1, 1, 0, 0],
        [1, 1, 0, 1, 1, 1, 0],
        [1, 1, 0, 0, 1, 1, 0],
        [0, 1, 0, 1, 0, 1, 0],
        [0, 0, 1, 0, 1, 1, 0]])

In [45]:
h=6 
w=5
pad_w_list = [int(w/2), int(w/2)] # 避免 w为奇数 除不尽的情况 如果为1 或0怎么处理 为0 后续则不取该图像 w-int(w/2)
# h=6时 中心点上取三行 中心点下取两行 h=7时 中心点上取三行 下取三行 可以少pad一行一列 [int(w/2), int(w/2)]
pad_h_list = [int(h/2), int(h/2)]
padding = torch.nn.ConstantPad2d((pad_w_list[0],pad_w_list[1],pad_h_list[0],pad_h_list[1]), 255)
gg=padding(g)
pad_w_list,gg

([2, 2],
 tensor([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
         [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
         [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
         [255, 255,   1,   1,   1,   1,   1,   1,   1,   1, 255, 255],
         [255, 255,   1,   0,   1,   0,   1,   1,   0,   1, 255, 255],
         [255, 255,   1,   0,   1,   1,   0,   0,   1,   0, 255, 255],
         [255, 255,   1,   1,   0,   1,   1,   1,   0,   0, 255, 255],
         [255, 255,   1,   1,   1,   0,   1,   1,   1,   0, 255, 255],
         [255, 255,   1,   1,   1,   0,   0,   1,   1,   0, 255, 255],
         [255, 255,   1,   0,   1,   0,   1,   0,   1,   0, 255, 255],
         [255, 255,   1,   0,   0,   1,   0,   1,   1,   0, 255, 255],
         [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
         [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
         [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255

In [47]:
center_y = torch.randint( int(h/2) + minrow, int(h/2) + maxrow + 1,[] ) # get center point 均匀分布 还是正态分布
center_x = torch.randint( int(w/2) + mincol, int(w/2) + maxcol + 1, [] ) 
                                                                                                
# 截取区域
new_max_row = center_y + (h-int(h/2))
new_min_row = center_y - int(h/2)
new_max_col = center_x + (w-int(w/2)) # 不需减一 因为后续提取位置会加一 
new_min_col = center_x - int(w/2)
center_y,center_x,new_max_row,new_min_row,new_max_col,new_min_col

(tensor(10), tensor(7), tensor(13), tensor(7), tensor(10), tensor(5))

In [85]:
aa=gg[ int(h/2)+minrow:int(h/2)+maxrow+1,int(w/2)+mincol:int(w/2)+maxcol+1] # 目标范围
aa

tensor([[0, 1, 0, 1, 1, 0, 1],
        [0, 1, 1, 0, 0, 1, 0],
        [1, 0, 1, 1, 1, 0, 0],
        [1, 1, 0, 1, 1, 1, 0],
        [1, 1, 0, 0, 1, 1, 0],
        [0, 1, 0, 1, 0, 1, 0],
        [0, 0, 1, 0, 1, 1, 0]])

In [87]:
ggg=gg[new_min_row:new_max_row,new_min_col:new_max_col]
ggg

tensor([[  0,   1,   1,   1,   0],
        [  0,   0,   1,   1,   0],
        [  0,   1,   0,   1,   0],
        [  1,   0,   1,   1,   0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]])

In [76]:
##### attentive
features = torch.ones(4,4)
features[1,2] =10 
features

tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1., 10.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])

In [77]:
att_idx = torch.argmax(features)
att_idx


tensor(6)

In [80]:
att_size = features.size(1) # 获取列的宽度
row = torch.div(att_idx,att_size,rounding_mode='floor')
col = att_idx % att_size
att_size,row,col

(4, tensor(1), tensor(2))

In [81]:
att_idx = torch.cat([ row.unsqueeze(0),   #[100,1,27] 除数 实际是反flatten 代表行数
          col.unsqueeze(0),], dim=0)      #[100,1,27] 余数 代表列数 [4，2] 如果设计为tok 则为[4,2,tok]
att_idx

tensor([1, 2])

In [88]:
h=6 
w=5
pad_w_list = [int(w/2), int(w/2)] # 避免 w为奇数 除不尽的情况 如果为1 或0怎么处理 为0 后续则不取该图像 w-int(w/2)
# h=6时 中心点上取三行 中心点下取两行 h=7时 中心点上取三行 下取三行 可以少pad一行一列 [int(w/2), int(w/2)]
pad_h_list = [int(h/2), int(h/2)]
padding = torch.nn.ConstantPad2d((pad_w_list[0],pad_w_list[1],pad_h_list[0],pad_h_list[1]), 255)
pad_F=padding(features)
pad_w_list, pad_F

([2, 2],
 tensor([[255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255.,   1.,   1.,   1.,   1., 255., 255.],
         [255., 255.,   1.,   1.,  10.,   1., 255., 255.],
         [255., 255.,   1.,   1.,   1.,   1., 255., 255.],
         [255., 255.,   1.,   1.,   1.,   1., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255.],
         [255., 255., 255., 255., 255., 255., 255., 255.]]))

In [90]:
center_y = att_idx[ 0]+int(h/2)
center_x = att_idx[ 1]+int(w/2)
center_x,center_y

(tensor(4), tensor(4))

In [91]:
new_max_row = center_y + (h-int(h/2))
new_min_row = center_y - int(h/2)
new_max_col = center_x + (w-int(w/2)) # 不需减一 因为后续提取位置会加一 
new_min_col = center_x - int(w/2)
new_max_col,new_min_col,new_max_row,new_min_row

(tensor(7), tensor(2), tensor(7), tensor(1))

In [92]:
attarea=pad_F[new_min_row:new_max_row,new_min_col:new_max_col]
attarea

tensor([[255., 255., 255., 255., 255.],
        [255., 255., 255., 255., 255.],
        [  1.,   1.,   1.,   1., 255.],
        [  1.,   1.,  10.,   1., 255.],
        [  1.,   1.,   1.,   1., 255.],
        [  1.,   1.,   1.,   1., 255.]])

In [ ]:
att_idx = torch.argmax(features)
att_idx
att_size = features[1] # 获取列的宽度
att_idx = torch.cat([ (att_idx // att_size).unsqueeze(1),   #[100,1,27] 除数 实际是反flatten 代表行数
          (att_idx  % att_size).unsqueeze(1),], dim=1)      #[100,1,27] 余数 代表列数 [4，2] 如果设计为tok 则为[4,2,tok]
att_idx

In [27]:
import numpy as np
b= np.array([[1,1,1],[1,0,1],[0,1,1],[0,1,0],[1,1,1]])
nprow =np.min(b,axis=1)
nprow
npcol=np.min(b,axis=0)
npcol


array([0, 0, 0])

In [30]:
mn_row=np.argmin(nprow)
mx_row=nprow.shape[0]-np.argmin(nprow[::-1])-1
mn_row,mx_row


(1, 3)

In [31]:
mn_col=np.argmin(npcol)
mx_col=npcol.shape[0]-np.argmin(npcol[::-1])-1
mn_col,mx_col

(0, 2)